### ISSUE TITLE
Forza UDP

### ISSUE THREAD

**Issue by arilink-tech** [ItsLogic/Forza-Telemetry#1]
Hello, I am also trying to access the telemetry data of Horizon 4 recently. I finally read the UDP data by turning off the firewall and other operations on one of my computers, but it won’t work when I switch to another computer. , Have you ever encountered a similar problem?

**Comment by ItsLogic** [comment]
I havent ever encountered anything like that. While testing everything just sort of worked so I didnt need to change any settings.

Do you have a list of things you had to change to get it working and some info about your operating system install? Having more information would make it easier to figure out whats causing the issue. Ive only tested on my system so I have no idea how other setups impact the functionality.

**Comment by arilink-tech** [comment]
I tried a lot of operations at the time, but it happened occasionally. I can’t remember exactly how to do it. It’s a weird question.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ItsLogic/Forza-Telemetry"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:28
收件人:&nbsp;"ItsLogic/Forza-Telemetry"<Forza-Telemetry@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ItsLogic/Forza-Telemetry] Forza UDP (#1)





 
I havent ever encountered anything like that. While testing everything just sort of worked so I didnt need to change any settings.
 
Do you have a list of things you had to change to get it working and some info about your operating system install? Having more information would make it easier to figure out whats causing the issue. Ive only tested on my system so I have no idea how other setups impact the functionality.

**Comment by TLRxModzZ** [comment]
![image](https://user-images.githubusercontent.com/77285392/104384485-7206cb00-5529-11eb-97b3-0a06e246c6e5.png)


> I tried a lot of operations at the time, but it happened occasionally. I can’t remember exactly how to do it. It’s a weird question.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ItsLogic/Forza-Telemetry" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:28 收件人:&nbsp;"ItsLogic/Forza-Telemetry"<Forza-Telemetry@noreply.github.com&gt;; 抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [ItsLogic/Forza-Telemetry] Forza UDP (#1) I havent ever encountered anything like that. While testing everything just sort of worked so I didnt need to change any settings. Do you have a list of things you had to change to get it working and some info about your operating system install? Having more information would make it easier to figure out whats causing the issue. Ive only tested on my system so I have no idea how other setups impact the functionality. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi, 
i was having the same problems and spent my whole day trouble shooting. any who below you can find a screen shot to the solution that worked for me! and it seems to work for alot of other people as well! one of the things i should mention is that i didnt need to turn off my firewall or anti virus either to make this work. im pretty sure it has something to do with MS games not allowing you to send data to your pc etc.
link to it is here: https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#forza-horizon-4--motorsport-7
I hope this helps you!

**Comment by ItsLogic** [comment]
Closing this issue since this was most likely the problem. 

Please comment and I will reopen if it was not.
